version: '3.8'

services:
  js-express-server:
    build:
      context: ./js-express-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./js-express-server:/app
    environment:
      - NODE_ENV=development
      - PORT=8000
